<?php
    $doc = new DOMDocument();
    $doc->formatOutput = true;
    $root_element = $doc->createElement("authentication");
    $doc->appendChild($root_element);

    $accountElement = $doc->createElement("status");
    $accountElement->appendChild($doc->createTextNode($this->msg->status));
    $root_element->appendChild($accountElement);
    $accountElement = $doc->createElement("info");
    $accountElement->appendChild($doc->createTextNode($this->msg->info));
    $root_element->appendChild($accountElement);
    print $doc->saveXML();    
?>
