<?php
    $doc = new DOMDocument();
    $doc->formatOutput = true;
    $root_element = $doc->createElement("authentication");
    $doc->appendChild($root_element);

    $transactionElement = $doc->createElement("status");
    $transactionElement->appendChild($doc->createTextNode($this->msg->status));
    $root_element->appendChild($transactionElement);
    $transactionElement = $doc->createElement("info");
    $transactionElement->appendChild($doc->createTextNode($this->msg->info));
    $root_element->appendChild($transactionElement);
    print $doc->saveXML();    
?>
