<?php
    header("Content-Type: text/html");
    echo '<!DOCTYPE html>';
    echo '<html>';
    echo '<body>';
    echo '<div id="account">';                  
        echo 'status='.$this->msg->status.'<br>';    
        echo 'accountId='.$this->msg->id.'<br>';
        echo 'balance='.$this->msg->balance.'<br>';
    echo '</div>';                          
    echo '</body>';
    echo '</html>';
    exit;
?>