<?php

$doc = new DOMDocument();
$doc->formatOutput = true;
$root_element = $doc->createElement("response");
$doc->appendChild($root_element);

$accountElement = $doc->createElement("status");
$accountElement->appendChild($doc->createTextNode($this->msg->status));
$root_element->appendChild($accountElement);
$accountElement = $doc->createElement("accountid");
$accountElement->appendChild($doc->createTextNode($this->msg->id));
$root_element->appendChild($accountElement);
$accountElement = $doc->createElement("owner");
$accountElement->appendChild($doc->createTextNode($this->msg->owner));
$root_element->appendChild($accountElement);
$accountElement = $doc->createElement("balance");
$accountElement->appendChild($doc->createTextNode($this->msg->balance));
$root_element->appendChild($accountElement);

print $doc->saveXML();
?>
