<?php    
    $doc = new DOMDocument();
    
    $doc->formatOutput = $this->format;
    
    $responseElement = $doc->createElement("response");
    
    $status = $doc->createElement("status");
    $status->appendChild($doc->createTextNode($this->msg['status']));
    
    $accounts = $doc->createElement("accounts");
    
    foreach($this->msg['accounts'] as $account) {       
        $transactionElement = $doc->createElement('account');
        
        $transactionElement->setAttribute('id',$account['id']);
        $transactionElement->setAttribute('balance',$account['balance']);
        
        $accounts->appendChild($transactionElement);
    }
        
    $responseElement->appendChild($status);
    $responseElement->appendChild($accounts);
    
    $doc->appendChild($responseElement);
    
    echo $doc->saveXML();    
?>
