<?php
    header("Content-Type: text/html");
    echo '<!DOCTYPE html>';
    echo '<html>';
    echo '<body';
    echo '<div id="transaction">';                  
    echo 'status='.$this->msg->status.'<br>';    
    reset($this->msg->transactions);
    while(list($key, $val) = each($this->msg->transactions)){
        while(list($keys, $vals) = each($val)){            
            echo $keys.'='.$vals.'::';
        }
        echo '<br>';            
    }
    echo '</div>';                          
    echo '</body>';
    echo '</html>';
    exit;
?>
