<!DOCTYPE html>

<html>
    <body
    <div id="transaction">                  
    <?php
        echo 'status='.$this->msg->status.'<br>';    
        reset($this->msg->transactions);
        while(list($key, $val) = each($this->msg->transactions)){
            while(list($keys, $vals) = each($val)){            
                echo $keys.'='.$vals.'::';
            }
            echo '<br>';            
        }
    ?>
    </div>                          
</body>
</html>