<!DOCTYPE html>
<html>
<body   
<div id="status"><?php echo $this->msg['status']; ?></div>    
<div id="accounts">
<table>
    <thead>
        <tr>
        <?php foreach (Application_Model_Transaction::keys() as $key) : ?>
            <td><?php echo $key; ?></td>
        <?php endforeach; ?>    
        </tr>
    </thead>        
    
    <tbody>
    <?php foreach ($this->msg['transactions'] as $transaction) : ?>
        <tr>
        <?php foreach ($transaction as $key => $value) : ?>
            <td><?php echo $value; ?></td>
        <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>    
</table>    
</div>                          
</body>
</html>