<?php    
    $doc = new DOMDocument();
    
    $doc->formatOutput = $this->format;            
    
    $responseElement = $doc->createElement("response");
    
    $status = $doc->createElement("status");
    $status->appendChild($doc->createTextNode($this->msg['status']));
    
    $accounts = $doc->createElement("transactions");
    
    foreach($this->msg['transactions'] as $transaction) {       
        $transactionElement = $doc->createElement('account');
        
        foreach($transaction as $key => $value ) {
            $transactionElement->setAttribute($key,$value);    
        }       
        
        $accounts->appendChild($transactionElement);
    }
        
    $responseElement->appendChild($status);
    $responseElement->appendChild($accounts);
    
    $doc->appendChild($responseElement);
    
    echo $doc->saveXML();   
?>

